name: 'ci-pull-request'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  controller-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Run controller tests
        run: npm run testes-controller

  integration-tests:
      runs-on: ubuntu-latest
      needs: [controller-tests]
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install
    
      - name: Start server
        run: npm run start & sleep 5

      - name: Run integration tests
        run: npm run testes-external
   